[SERVICE]
    flush        1
    log_level    info
    daemon       off
    parsers_file /fluent-bit/etc/parsers.conf

[INPUT]
    name              tail
    path              /var/lib/docker/containers/*/*.log
    parser            docker
    tag               docker.*
    read_from_head    true
    db                /fluent-bit/state/flb_kube.db

[FILTER]
    name              modify
    match             *
    add               container_name app-java

[OUTPUT]
    name              loki
    match             *
    host              loki
    port              3100
    uri               /loki/api/v1/push
    tenant_id         fluentbit
    labels            job=fluentbit,container_name=$container_name
    label_keys        container_name
    line_format       json
