extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: http://jaeger:9411/api/v2/spans

processors:
  batch:

service:
  extensions: [health_check]   # 👈 activa la extensión
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
