version: '3.8'
services:
  app-java:
    build:
      context: ./app-java
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=app-java
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_METRICS_EXPORTER=none
    depends_on:
      - otel-collector
    networks:
      - observabilidad-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "55681:55681"
    networks:
      - observabilidad-net

  jaeger:
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686"
      - "14250:14250"
      - "9411:9411"  
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411            
    networks:
      - observabilidad-net

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - ./loki/data:/loki         # <-- esto monta todo lo necesario
    command: -config.file=/etc/loki/config.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - loki      

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail/config-promtail.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki      

networks:
  observabilidad-net:
    driver: bridge
